import React, { useEffect, useState, useRef, useCallback } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import Sidebar from '../../components/shared/Sidebar';
import { getMySubjectEnrollments, joinSubject, getSessionsBySubject, markAttendanceFace, markAttendanceQR } from '../../services/api';
import Webcam from 'react-webcam';
import * as faceapi from 'face-api.js';
import jsQR from 'jsqr';

/**
 * Extracts the raw 32-char hex token from ANY of these formats:
 *   1. ?token=abc123                  (query param — generated by teacher's copy button)
 *   2. http://localhost:3000/join/abc123  (full URL pasted by student)
 *   3. /join/abc123                   (relative path pasted by student)
 *   4. abc123                         (raw token pasted directly)
 */
function extractToken(raw) {
  if (!raw) return '';
  const trimmed = raw.trim();

  // Try query param first (?token=xxx)
  try {
    const url = new URL(trimmed, window.location.origin);
    const qp = url.searchParams.get('token');
    if (qp) return qp;

    // Try /join/:token path segment
    const match = url.pathname.match(/\/join\/([a-f0-9]{16,})/i);
    if (match) return match[1];
  } catch (_) {
    // Not a parseable URL — fall through
  }

  // Match a bare hex token anywhere in the string
  const hexMatch = trimmed.match(/([a-f0-9]{16,})/i);
  if (hexMatch) return hexMatch[1];

  return trimmed; // return as-is; server will reject if invalid
}


// ─── Real Camera QR Scanner ───────────────────────────────────────────────────
// Uses device camera, decodes QR frame-by-frame using jsQR, then calls the API
function QRScannerSection({ sessionId, onSuccess, onError, onCancel }) {
  const videoRef = useRef(null);
  const canvasRef = useRef(null);
  const streamRef = useRef(null);
  const scanLoopRef = useRef(null);
  const [scanning, setScanning] = useState(false);
  const [statusMsg, setStatusMsg] = useState('Starting camera…');
  const [cameraError, setCameraError] = useState('');

  useEffect(() => {
    let active = true;
    // Prefer back camera on mobile; fall back to any available camera
    const startCamera = async () => {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } });
        if (!active) { stream.getTracks().forEach(t => t.stop()); return; }
        streamRef.current = stream;
        if (videoRef.current) videoRef.current.srcObject = stream;
        setStatusMsg('Point camera at the QR code…');
      } catch {
        try {
          const stream = await navigator.mediaDevices.getUserMedia({ video: true });
          if (!active) { stream.getTracks().forEach(t => t.stop()); return; }
          streamRef.current = stream;
          if (videoRef.current) videoRef.current.srcObject = stream;
          setStatusMsg('Point camera at the QR code…');
        } catch {
          setCameraError('Camera access denied. Enable camera permission or use manual entry below.');
        }
      }
    };
    startCamera();
    return () => {
      active = false;
      if (streamRef.current) streamRef.current.getTracks().forEach(t => t.stop());
      if (scanLoopRef.current) cancelAnimationFrame(scanLoopRef.current);
    };
  }, []);

  const scanFrame = useCallback(async () => {
    const video = videoRef.current;
    const canvas = canvasRef.current;
    if (!video || !canvas || video.readyState !== 4) {
      scanLoopRef.current = requestAnimationFrame(scanFrame);
      return;
    }
    canvas.width = video.videoWidth;
    canvas.height = video.videoHeight;
    const ctx = canvas.getContext('2d');
    ctx.drawImage(video, 0, 0);
    const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
    const code = jsQR(imageData.data, imageData.width, imageData.height);
    if (code) {
      // Found a QR code — stop scanning and submit
      if (streamRef.current) streamRef.current.getTracks().forEach(t => t.stop());
      cancelAnimationFrame(scanLoopRef.current);
      setScanning(true);
      setStatusMsg('QR detected! Verifying…');
      try {
        const { markAttendanceQR } = await import('../../services/api');
        await markAttendanceQR({ sessionId, qrToken: code.data });
        onSuccess();
      } catch (err) {
        const msg = err.response?.data?.message || 'QR verification failed';
        if (msg.toLowerCase().includes('already')) {
          onError('Attendance already marked for this session.');
        } else {
          onError(msg);
        }
        onCancel();
      }
    } else {
      scanLoopRef.current = requestAnimationFrame(scanFrame);
    }
  }, [sessionId, onSuccess, onError, onCancel]);

  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    const handlePlay = () => { scanLoopRef.current = requestAnimationFrame(scanFrame); };
    video.addEventListener('play', handlePlay);
    return () => video.removeEventListener('play', handlePlay);
  }, [scanFrame]);

  return (
    <div style={{ textAlign: 'center' }}>
      {cameraError ? (
        <div>
          <div className="alert alert-error">{cameraError}</div>
          <ManualQREntry sessionId={sessionId} onSuccess={onSuccess} onError={onError} />
        </div>
      ) : (
        <div>
          <p style={{ color: '#555', fontSize: 13, marginBottom: 12 }}>{statusMsg}</p>
          <div style={{ position: 'relative', display: 'inline-block', borderRadius: 12, overflow: 'hidden' }}>
            <video ref={videoRef} autoPlay playsInline muted
              style={{ width: '100%', maxWidth: 340, aspectRatio: '340 / 260', objectFit: 'cover', display: 'block', borderRadius: 12 }} />
            {/* Scan overlay */}
            <div style={{
              position: 'absolute', top: '50%', left: '50%',
              transform: 'translate(-50%, -50%)',
              width: 180, height: 180,
              border: '3px solid #4facfe',
              borderRadius: 12,
              boxShadow: '0 0 0 2000px rgba(0,0,0,0.25)',
              pointerEvents: 'none'
            }} />
            {scanning && (
              <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.5)' }}>
                <div style={{ color: '#fff', fontWeight: 700, fontSize: 15 }}>⏳ Verifying…</div>
              </div>
            )}
          </div>
          <canvas ref={canvasRef} style={{ display: 'none' }} />
          <p style={{ fontSize: 12, color: '#888', marginTop: 8 }}>
            Hold the QR code steady inside the blue box.
          </p>
        </div>
      )}
    </div>
  );
}

function ManualQREntry({ sessionId, onSuccess, onError }) {
  const [val, setVal] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!val.trim()) return;
    setSubmitting(true);
    try {
      const { markAttendanceQR } = await import('../../services/api');
      await markAttendanceQR({ sessionId, qrToken: val.trim() });
      onSuccess();
    } catch (err) {
      onError(err.response?.data?.message || 'Invalid QR token');
    } finally { setSubmitting(false); }
  };
  return (
    <form onSubmit={handleSubmit} style={{ marginTop: 16, textAlign: 'left' }}>
      <div className="form-group">
        <label>Manual QR Token Entry</label>
        <input value={val} onChange={e => setVal(e.target.value)} placeholder="Paste QR token if camera fails" />
      </div>
      <button type="submit" className="btn btn-primary" disabled={submitting}>{submitting ? 'Submitting…' : 'Submit Token'}</button>
    </form>
  );
}

export default function StudentSubjects() {
  const location = useLocation();
  const navigate = useNavigate();
  const [subjects, setSubjects] = useState([]);
  const [loading, setLoading] = useState(true);
  const [token, setToken] = useState('');
  const [joining, setJoining] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [activeSession, setActiveSession] = useState(null);
  const [attendanceSubject, setAttendanceSubject] = useState(null);
  const [scanning, setScanning] = useState(false);
  const [qrToken, setQrToken] = useState('');
  const [modelsLoaded, setModelsLoaded] = useState(false);
  const [facingMode, setFacingMode] = useState('environment');
  const webcamRef = useRef(null);
  const autoJoinRan = useRef(false); // prevent double-firing in StrictMode

  // ─── FIX 1: Extract token from URL on mount ──────────────────────────────
  // Handles both ?token=xxx (generated link) and /join/:token (path format)
  useEffect(() => {
    // Query param: /student/subjects?token=abc
    const params = new URLSearchParams(location.search);
    const qpToken = params.get('token');

    // Path param: /join/abc  (handled by a route in App.js, passed via state)
    const stateToken = location.state?.inviteToken;

    const found = qpToken || stateToken || '';
    if (found) {
      setToken(found);
    }
  }, [location]);

  // ─── FIX 2: Auto-submit when token arrives from a clicked link ────────────
  useEffect(() => {
    if (token && !autoJoinRan.current) {
      autoJoinRan.current = true;
      handleJoinWithToken(token);
    }
  }, [token]); // eslint-disable-line react-hooks/exhaustive-deps

  const fetchSubjects = async () => {
    try {
      const res = await getMySubjectEnrollments();
      setSubjects(res.data);
    } catch (err) {
      setError('Failed to load subjects');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchSubjects(); }, []);

  // Load face-api.js models
  useEffect(() => {
    const loadModels = async () => {
      try {
        await faceapi.nets.ssdMobilenetv1.loadFromUri('/models');
        await faceapi.nets.faceLandmark68Net.loadFromUri('/models');
        await faceapi.nets.faceRecognitionNet.loadFromUri('/models');
        setModelsLoaded(true);
      } catch (err) {
        console.warn('Face models not loaded:', err.message);
      }
    };
    loadModels();
  }, []);

  // Core join logic — accepts a raw input (full URL, path, or bare token)
  const handleJoinWithToken = async (rawToken) => {
    const cleanToken = extractToken(rawToken);
    if (!cleanToken) { setError('No valid token found in that input.'); return; }
    setError(''); setSuccess(''); setJoining(true);
    try {
      await joinSubject({ inviteToken: cleanToken });
      setSuccess('✅ Joined subject successfully! It now appears below.');
      setToken('');
      navigate('/student/subjects', { replace: true });
      fetchSubjects();
    } catch (err) {
      const msg = err.response?.data?.message || 'Error joining subject';
      if (msg.toLowerCase().includes('already')) {
        setSuccess('ℹ️ You are already enrolled in this subject.');
        setToken('');
        navigate('/student/subjects', { replace: true });
      } else {
        setError(msg);
      }
    } finally {
      setJoining(false);
    }
  };

  // Form submit handler — user clicked "Join Subject" button manually
  const handleJoin = async (e) => {
    e.preventDefault();
    autoJoinRan.current = true;
    await handleJoinWithToken(token);
  };

  const handleStartAttendance = async (subjectEnrollment) => {
    try {
      const res = await getSessionsBySubject(subjectEnrollment.subject._id);
      const active = res.data.find(s => s.status === 'active');
      if (!active) return alert('No active session for this subject right now.');
      setActiveSession(active);
      setAttendanceSubject(subjectEnrollment);
    } catch (err) {
      alert('Error checking session');
    }
  };

  const handleFaceScan = async () => {
    if (!modelsLoaded) return alert('Face recognition models not loaded. Please try again.');
    if (!webcamRef.current) return;
    setScanning(true);
    try {
      const imageSrc = webcamRef.current.getScreenshot();
      const img = await faceapi.fetchImage(imageSrc);
      const detection = await faceapi.detectSingleFace(img).withFaceLandmarks().withFaceDescriptor();

      if (!detection) {
        alert('No face detected. Please ensure your face is visible.');
        setScanning(false);
        return;
      }

      const embedding = Array.from(detection.descriptor);
      const res = await markAttendanceFace({
        sessionId: activeSession._id,
        embedding,
        confidenceScore: 0.85 // Server will do actual comparison, this is placeholder
      });

      setSuccess('Attendance marked via face recognition! ✓');
      setActiveSession(null);
    } catch (err) {
      if (err.response?.data?.duplicate) {
        alert('Attendance already marked for this session!');
      } else {
        setError(err.response?.data?.message || 'Face recognition failed');
      }
    } finally {
      setScanning(false);
    }
  };

  const handleQRAttendance = async () => {
    if (!qrToken.trim()) return alert('Enter QR token');
    try {
      await markAttendanceQR({ sessionId: activeSession._id, qrToken: qrToken.trim() });
      setSuccess('Attendance marked via QR! ✓');
      setActiveSession(null);
      setQrToken('');
    } catch (err) {
      setError(err.response?.data?.message || 'QR attendance failed');
    }
  };

  return (
    <div className="app">
      <Sidebar />
      <div className="main-content">
        <div className="page-header">
          <h1>📖 My Subjects</h1>
        </div>

        {error && <div className="alert alert-error">{error}</div>}
        {success && <div className="alert alert-success">{success}</div>}

        <div className="card">
          <div className="card-title">Join Subject via Invite Link</div>
          <p style={{ fontSize: 13, color: '#888', marginBottom: 12 }}>
            Paste the full invite link <em>or</em> just the token your teacher shared.
            
          </p>
          <form onSubmit={handleJoin} className="inline-form">
            <input
              value={token}
              onChange={e => { autoJoinRan.current = false; setToken(e.target.value); }}
              placeholder="Paste full invite link or token here…"
              style={{ flex: 1, padding: '9px 14px', border: '1px solid #ddd', borderRadius: 8, fontSize: 14 }}
              required
            />
            <button type="submit" className="btn btn-primary" disabled={joining}>
              {joining ? 'Joining…' : 'Join Subject'}
            </button>
          </form>
        </div>

        {loading ? <div className="spinner" /> : (
          <div className="cards-grid">
            {subjects.map(e => (
              <div className="item-card" key={e._id}>
                <div className="item-card-title">{e.subject?.subjectName}</div>
                {e.subject?.subjectCode && <div className="item-card-desc">{e.subject.subjectCode}</div>}
                <div className="item-card-meta">Course: {e.subject?.courseId}</div>
                <div className="item-card-actions">
                  <button className="btn btn-primary btn-sm" onClick={() => handleStartAttendance(e)}>
                  📷 Mark Attendance
                  </button>
                </div>
              </div>
            ))}
            {subjects.length === 0 && (
              <div style={{ color: '#888', padding: 20 }}>No subjects yet. Join one using an invite link!</div>
            )}
          </div>
        )}

        {/* Attendance Modal */}
        {activeSession && (
          <div className="modal-overlay" onClick={() => setActiveSession(null)}>
            <div className="modal" style={{ maxWidth: 560 }} onClick={e => e.stopPropagation()}>
              <h3>📷 Mark Attendance — {attendanceSubject?.subject?.subjectName}</h3>
              <p style={{ color: '#888', fontSize: 13, marginBottom: 16 }}>
                Mode: <strong>{activeSession.mode}</strong>
              </p>

              {(activeSession.mode === 'face' || activeSession.mode === 'manual') && (
                <div>
                  <div className="webcam-container" style={{ textAlign: 'center', marginBottom: 16 }}>
                    <Webcam
                      ref={webcamRef}
                      screenshotFormat="image/jpeg"
                      videoConstraints={{ facingMode }}
                      style={{ width: '100%', maxWidth: 420, aspectRatio: '4 / 3', height: 'auto', borderRadius: 12, display: 'block', margin: '0 auto' }}
                    />
                  </div>
                  <div style={{ display: 'flex', gap: 8, marginBottom: 12 }}>
                    <button
                      className="btn btn-primary"
                      style={{ flex: 1, justifyContent: 'center' }}
                      onClick={handleFaceScan}
                      disabled={scanning || !modelsLoaded}
                    >
                      {scanning ? 'Scanning...' : modelsLoaded ? '📸 Scan Face' : 'Loading models...'}
                    </button>
                    <button
                      className="btn btn-outline"
                      onClick={() => setFacingMode(prev => prev === 'user' ? 'environment' : 'user')}
                      title="Switch camera"
                    >
                      🔄
                    </button>
                  </div>
                  {!modelsLoaded && (
                    <p style={{ fontSize: 12, color: '#888', textAlign: 'center', marginTop: 8 }}>
                      Face recognition models loading... Ensure /public/models has face-api.js model files.
                    </p>
                  )}
                </div>
              )}

              {activeSession.mode === 'qr' && (
                <QRScannerSection
                  sessionId={activeSession._id}
                  onSuccess={() => { setSuccess('✅ QR attendance marked!'); setActiveSession(null); }}
                  onError={(msg) => setError(msg)}
                  onCancel={() => setActiveSession(null)}
                />
              )}

              <button className="btn btn-outline" style={{ marginTop: 12 }} onClick={() => setActiveSession(null)}>Cancel</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
